#!/bin/bash

echo "Image build starting"

n=$(od -An -N1 -i /dev/urandom | awk '{print $1 % 10}' | head -n 1)

if [ "$n" -lt 5 ]; then
  echo "❌ Failure!"
  exit 1
else
  echo "✅ Success!"
  exit 0
fi
