name: Check for manual api changes

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  merge_group:

# this prevents multiple jobs from the same pr
# running when new changes are pushed.
concurrency:
  group: ${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-manual-changes:
    name: Manual API changes check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: Install bun
      run: npm install -g bun
    - name: Install dependencies
      run: bun install
    - name: Detect API changes
      run: |
        bun generate
        if [ -n "$(git status --porcelain)" ]; then
          echo
          echo "✗ API manually changed, please run 'bun generate' to generate the API types & endpoints"
          exit 1
        fi
        echo
        echo "✓ No manual API changes detected"
