name: Run integration tests

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  merge_group:

# this prevents multiple jobs from the same pr
# running when new changes are pushed.
concurrency:
  group: ${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration-tests:
    name: Integration Tests (${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - arch: x86_64
            runner: ubuntu-24.04
          - arch: aarch64
            runner: ubuntu-24.04-arm
    container: registry.fedoraproject.org/fedora:latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: Install image-builder
      run: dnf install -y image-builder
    - name: Check image-builder
      run: image-builder --version
    - name: Install bun
      run: npm install -g bun
    - name: Install dependencies
      run: bun install
    - name: Run integration tests
      run: bun test:integration
